// File: src/constants.js
export const APP_STATE = {
  WELCOME: 'WELCOME',
  WIZARD: 'WIZARD',
  RESULTS: 'RESULTS',
  AUTH: 'AUTH',
  DASHBOARD: 'DASHBOARD',
  THERAPIST_DASHBOARD: 'THERAPIST_DASHBOARD',
  THERAPIST_ONBOARDING: 'THERAPIST_ONBOARDING',
  SAVED_MATCHES: 'SAVED_MATCHES'
};

export const ROLES = {
  PATIENT: 'patient',
  THERAPIST: 'therapist'
};

